### ISSUE TITLE
Contrary to README, library is not available on CPAN

### ISSUE THREAD

**Issue by jkeenan** [briandfoy/ghojo#17]
The README includes this:

```
You can read the documentation and inspect the meta data on one of the CPAN web interfaces, such as CPAN Search or MetaCPAN:

    http://search.cpan.org/dist/Ghojo
    http://www.metacpan.org/module/Ghojo

The standard module documentation has example uses in the SYNOPSIS section, but you can also look in the examples/ directory (if it's there), or look at the test files in t/.
Installation

You can install this module with a CPAN client, which will resolve and install the dependencies:

        % cpan Ghojo
        % cpanm Ghojo
```

However, both of those links give 404s, so the library is not yet installable from CPAN.

This was noted in the course of a discussion on the [Madrid Perlmongers mailing list](http://mail.pm.org/pipermail/madrid-pm/2016-October/002257.html).

Do you expect to put this on CPAN soon?

**Comment by briandfoy** [comment]
I want to hack on it a bit more. Maybe next week some time.

**Comment by briandfoy** [comment]
I'm closing this. I don't want to remove the badges only to put them back later.
